# Generated by Django 5.0.2 on 2024-03-09 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('Poland', 'Poland'), ('Germany', 'Germany'), ('France', 'France'), ('Spain', 'Spain'), ('Italy', 'Italy'), ('Czech Republic', 'Czech Republic'), ('Slovakia', 'Slovakia'), ('Austria', 'Austria'), ('Hungary', 'Hungary')], max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_app.businesstrip')),
            ],
        ),
    ]
