# Generated by Django 5.0.2 on 2024-03-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_alter_expense_business_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('PLN', 'Polish Zlot'), ('HUF', 'Hungarian Forint'), ('CZK', 'Czech Koruna'), ('RON', 'Romanian Leu')], default='USD', max_length=3),
            preserve_default=False,
        ),
    ]
